//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iauq.Information.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iauq.Information.App_GlobalResources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شما اجازه ارسال درخواست مورد نظر را ندارید..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قبلا رای داده‌اید..
        /// </summary>
        public static string AlreadyVoted {
            get {
                return ResourceManager.GetString("AlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار عددی مورد نیاز است..
        /// </summary>
        public static string ClientDataTypeModelValidatorProvider_FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در ثبت نظر شما مشکلی پیش آمده است. لطفا دوباره تلاش کنید..
        /// </summary>
        public static string CommentSubmissionFailure {
            get {
                return ResourceManager.GetString("CommentSubmissionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ایجاد مسیر مورد نظر وجود ندارد..
        /// </summary>
        public static string CreateDirectoryFailure {
            get {
                return ResourceManager.GetString("CreateDirectoryFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اطلاعات مورد نظر وجود ندارد. لطفا دوباره تلاش کنید..
        /// </summary>
        public static string CreationFailure {
            get {
                return ResourceManager.GetString("CreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف مسیر/فایل مورد نظر وجود ندارد..
        /// </summary>
        public static string DeleteDirectoryOrFileFailure {
            get {
                return ResourceManager.GetString("DeleteDirectoryOrFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات مورد نظر وجود ندارد. لطفا دوباره تلاش کنید..
        /// </summary>
        public static string DeleteFailure {
            get {
                return ResourceManager.GetString("DeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان دانلود فایل مورد نظر وجود ندارد..
        /// </summary>
        public static string DownloadFailure {
            get {
                return ResourceManager.GetString("DownloadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیری با این نام وجود دارد..
        /// </summary>
        public static string DuplicateDirectoryName {
            get {
                return ResourceManager.GetString("DuplicateDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایلی با این نام وجود دارد..
        /// </summary>
        public static string DuplicateFileName {
            get {
                return ResourceManager.GetString("DuplicateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی با شناسه مد نظر یافت نشد..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و/یا کلمه عبور وارد شده صحیح نمی باشد..
        /// </summary>
        public static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور قبلی وارد شده صحیح نمی باشد..
        /// </summary>
        public static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام پردازش درخواست.
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، متاسفانه در هنگام پردازش درخواست شما، خطایی در سیستم اتفاق افتاد است. لطفا مجددا تلاش نمائید..
        /// </summary>
        public static string InternalErrorDescription {
            get {
                return ResourceManager.GetString("InternalErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر امنیتی وارد شده اشتباه است..
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده صحیح نمی باشد. لطفا فیلد ها را مجددا مرور کرده و درخواست خود را دوباره ارسال نمائید..
        /// </summary>
        public static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} شامل کاراکترهای غیر مجاز می باشد..
        /// </summary>
        public static string NameHasInvalidFileNameChars {
            get {
                return ResourceManager.GetString("NameHasInvalidFileNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظری برای این مطلب ارسال نشده است..
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه و فایلی در این مسیر یافت نشد..
        /// </summary>
        public static string NoDirectoryOrFiles {
            get {
                return ResourceManager.GetString("NoDirectoryOrFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی شما نتیجه ای را در بر نداشت!.
        /// </summary>
        public static string NoMatchRecords {
            get {
                return ResourceManager.GetString("NoMatchRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرسنجی برای رای دادن یافت نشد..
        /// </summary>
        public static string NoPollFoundForVoting {
            get {
                return ResourceManager.GetString("NoPollFoundForVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای نمایش یافت نشد..
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلب مرتبطی یافت نشد..
        /// </summary>
        public static string NoRelated {
            get {
                return ResourceManager.GetString("NoRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه مد نظر یافت نشد..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، صفحه درخواست شده وجود ندارد. لطفا آدرس وارد شده را بررسی کرده و مجددا تلاش نمائید..
        /// </summary>
        public static string NotFoundDescription {
            get {
                return ResourceManager.GetString("NotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده مجاز نمی باشد..
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد نیاز..
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر نام مسیر/فایل مورد نظر وجود ندارد..
        /// </summary>
        public static string RenameFailure {
            get {
                return ResourceManager.GetString("RenameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای فایل انتخاب شده معتبر نمی باشد..
        /// </summary>
        public static string SelectedFileIsInvalid {
            get {
                return ResourceManager.GetString("SelectedFileIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب عکس ارسال شده مجاز نمی باشد..
        /// </summary>
        public static string SlideImageInvalidBinary {
            get {
                return ResourceManager.GetString("SlideImageInvalidBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم عکس انتخابی بیش از میزان مجاز است. (حداکثر 1MB).
        /// </summary>
        public static string SlideImageLength {
            get {
                return ResourceManager.GetString("SlideImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکسی انتخاب نشده است..
        /// </summary>
        public static string SlideImageRequired {
            get {
                return ResourceManager.GetString("SlideImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان بروز رسانی اطلاعات مورد نظر وجود ندارد. لطفا دوباره تلاش کنید..
        /// </summary>
        public static string UpdateFailure {
            get {
                return ResourceManager.GetString("UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ارسال فایل مورد نظر وجود ندارد..
        /// </summary>
        public static string UploadFileFailure {
            get {
                return ResourceManager.GetString("UploadFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل مورد نظر با موفقیت ارسال شد..
        /// </summary>
        public static string UploadFileSuccess {
            get {
                return ResourceManager.GetString("UploadFileSuccess", resourceCulture);
            }
        }
    }
}
